### ISSUE TITLE
I don't understand the instructions

### ISSUE THREAD

**Issue by boid-com** [another-guy/promisify-auth0#2]
const nativeAuthentication: NativeAuthentication = ...;

I've never seen this syntax...

**Comment by another-guy** [comment]
This line simply says that the code below will need the `nativeAuthentication` variable/constant of type NativeAuthentication.

`= ...` is pseudo code. It implies that `nativeAuthentication` is assigned to a non-null value.

If in your code that object is injected, or manually constructed, just use it. No special steps are needed.

**Comment by boid-com** [comment]
I'm not trying to be difficult, but the NativeAuthentication variable is defined in your example
import { Authentication as NativeAuthentication } from 'auth0-js';

So I don't understand why you included NativeAuthentication = ...;  

So are you saying nativeAuthentication = NativeAuthentication ?

**Comment by another-guy** [comment]
> I'm not trying to be difficult, but the NativeAuthentication variable is defined in your example
`import { Authentication as NativeAuthentication } from 'auth0-js'`;

No, `import { Authentication as NativeAuthentication } from 'auth0-js'` does **not** *define* a variable. 

Rather, it:
a) imports the type `Authentication` from `auth0-js`; and
b) aliases it ("renames it within the file scope") as `NativeAuthentication`.

There's no any kind of TypeScript variable involved here.

> So I don't understand why you included NativeAuthentication = ...;

If you already have a handle on a variable of type `Authentication` (`NativeAuthentication`) you don't need to declare it at all.

You should understand that this is a **pseudo-code**. If you want a better (context specific) explanation, show please show me how are you importing any `auth0-js` type in your code. I'll help.

> So are you saying nativeAuthentication = NativeAuthentication ?

No, I am not saying that "`nativeAuthentication = NativeAuthentication`". I am saying that `nativeAuthentication` should be of type `NativeAuthentication` (which is the `auth0-js`'s original type).

---

Here's a similar example (for another class):

```ts

import * as auth0 from 'auth0-js';
import { WebAuth } from 'promisify-auth0';

@Injectable()
export class AuthService {

  private readonly _authenticationOptionsForScope: auth0.AuthOptions = {
    clientID: 'someclientid',
    domain: 'secretdomain.auth0.com',
    responseType: 'token id_token',
    audience: 'https://secretdomain.com/',
    redirectUri: 'http://localhost:4200/callback',
    scope: 'openid profile permissions roles',
  };

  private readonly _wrappedWebAuth =
    new WebAuth(new auth0.WebAuth(this._authenticationOptionsForScope))

}

```

`_wrappedWebAuth` is now an instance of a promisified class... I.e. you can use it like this:

```ts
const loginResult = await this._wrappedWebAuth.login();
```

**Comment by boid-com** [comment]
Ok great, I really appreciate the extra explanation. I'm not familiar with ts so this is what threw me off.

**Comment by another-guy** [comment]
@Boid-John  yeah, no worries. Hope it helps. I'm closing the issue but feel free to reopen if you need more help.
